// Glossary data — the single source of truth for the report's terminology.
// Each entry is one dictionary term: an `id` (used for deep-linking from the
// inline "book-open" buttons), the visible `term`, an optional short gloss
// shown in the list, the full `definition`, and any external `sources`.
//
// `id`s match what `slugify` produces for the term, so an inline trigger can
// pass either the id or the term text and still resolve the right entry.
//
// User-facing copy carries no theorist or author names — frameworks are named
// neutrally (e.g. "Outcome-Driven Innovation (ODI)").

export interface GlossarySource {
  label: string
  href: string
}

export interface GlossaryTerm {
  id: string
  term: string
  /** One-line gloss shown under the term in the list. */
  short: string
  /** Full definition (paragraphs split on blank lines). */
  definition: string
  sources?: GlossarySource[]
}

// Authored unsorted; `glossaryTerms` exposes them alphabetically.
const terms: GlossaryTerm[] = [
  {
    id: 'confidence-level',
    term: 'Confidence Level',
    short: 'Calibrated confidence in a given Node42 output.',
    definition:
      'Confidence level describes how much certainty accompanies a specific output generated by Node42, expressed on a calibrated confidence scale (from tentative to almost certain). An insight might be highly interesting but come with a low confidence level — it therefore requires additional validation before it is acted on.',
  },
  {
    id: 'core-functional-job',
    term: 'Core Functional Job',
    short: 'The single overarching goal a stakeholder is trying to accomplish.',
    definition:
      'A core functional job (CFJ) is the single, overarching goal a stakeholder is ultimately trying to accomplish for a specific problem. The CFJ is phrased functionally, along its task-completion dimension, not along identity or emotion. It is solution-agnostic and serves as the anchor for the core, emotional, and status jobs associated with that stakeholder — for example, "dispense measured volumes of sterile drug product into primary containers under aseptic conditions".',
  },
  {
    id: 'core-jobs',
    term: 'Core Jobs',
    short: 'Solution-agnostic goals that feed into the core functional job.',
    definition:
      'Core jobs are the solution-agnostic goals a stakeholder is trying to accomplish — independent of any particular product or service. Per problem there is one core functional job, with several core jobs connecting into it, each adding detail to the overall goal.',
  },
  {
    id: 'emotional-jobs',
    term: 'Emotional Jobs',
    short: 'How a stakeholder wants to feel while getting the job done.',
    definition:
      'Emotional jobs are the immediate feelings a stakeholder wants to experience in the moment of getting a job done — how they want to feel right then, rather than what they want to accomplish.',
  },
  {
    id: 'status-jobs',
    term: 'Status Jobs',
    short: 'How a stakeholder wants to be perceived by others.',
    definition:
      'Status jobs are about how a stakeholder wants to be perceived by other people while getting a job done — how they look to others.',
  },
  {
    id: 'odi',
    term: 'ODI',
    short: 'Outcome-Driven Innovation.',
    definition:
      'ODI stands for Outcome-Driven Innovation — a Jobs-to-be-Done framework that treats a customer’s desired outcomes as measurable needs and scores each one on importance and satisfaction to reveal where the biggest innovation opportunities lie.',
  },
  {
    id: 'importance',
    term: 'Importance',
    short: 'How important a desired outcome is to a stakeholder (0–10).',
    definition:
      'Importance rates how important a specific desired outcome is to the stakeholder who holds it, on a 0–10 scale. It is one of the two inputs to the opportunity score; each rating carries its own rationale and calibrated confidence.',
  },
  {
    id: 'satisfaction',
    term: 'Satisfaction',
    short: 'How well a desired outcome is met today (0–10).',
    definition:
      'Satisfaction rates how well a desired outcome is met by the solutions available today, on a 0–10 scale. Paired with importance, it locates each need as underserved, served, or overserved.',
  },
  {
    id: 'opportunity-score',
    term: 'Opportunity Score',
    short: 'Where importance outruns satisfaction — the innovation signal.',
    definition:
      'The opportunity score combines importance and satisfaction to rank desired outcomes by how underserved and actionable they are. It is computed as importance + max(importance − satisfaction, 0): outcomes that are highly important yet poorly satisfied score highest and represent the strongest innovation opportunities.',
  },
  {
    id: 'innovation-status',
    term: 'Innovation Status',
    short: 'Underserved · served · overserved, from the importance–satisfaction gap.',
    definition:
      'Innovation status classifies each desired outcome from the gap between importance and satisfaction. Underserved: importance clearly exceeds satisfaction (a real opportunity). Overserved: satisfaction exceeds importance (likely over-invested). Served: satisfaction is roughly in line with importance (adequately met).',
  },
  {
    id: 'need-statement',
    term: 'Need Statement',
    short: 'A desired outcome phrased as a measurable need.',
    definition:
      'A need statement expresses a stakeholder’s desired outcome as a measurable need — a direction (minimize / increase), a metric, and the object of that metric, phrased independently of any solution. For example, "minimize the likelihood of a sterility-assurance breach going uncorrected during continuous dispensing".',
  },
  {
    id: 'error-statement',
    term: 'Error Statement',
    short: 'The failure a stakeholder is trying to avoid on a job.',
    definition:
      'An error statement captures the failure mode a stakeholder is trying to avoid while getting a job done — the thing that goes wrong (a delay, a defect, a breach). Each error statement is paired with its measurable need statement and carries an error type.',
  },
  {
    id: 'stakeholder-role',
    term: 'Stakeholder Role',
    short: 'A role in the buying centre with a distinct relationship to the job.',
    definition:
      'A stakeholder role is a distinct role in a market’s buying centre, each with its own relationship to the job. Node42 uses four: job executor (operates the system day to day), job overseer (governs safety and quality), purchase influencer (shapes specification and vendor choice), and purchase executor (holds budget and signs the purchase). Each role is anchored to an ESCO occupation code.',
  },
  {
    id: 'esco-code',
    term: 'ESCO Code',
    short: 'European skills, competences & occupations classification.',
    definition:
      'An ESCO code (European Skills, Competences, Qualifications and Occupations) is an identifier published by the European Commission for the building blocks of the EU labour market. It classifies occupations and the skills linked to them, allowing an apples-to-apples comparison of jobs across countries, languages, and platforms irrespective of local job titles.',
    sources: [{ label: 'ec.europa.eu/esco', href: 'https://esco.ec.europa.eu/en' }],
  },
  {
    id: 'market',
    term: 'Market',
    short: 'People or organizations trying to get a specific job done.',
    definition:
      'A market is a set of people or organizations trying to get a specific job done, defined by the outcomes they want to achieve — not by the product category, technology, or industry vertical that currently serves them. NAICS codes are used to practically identify and scope markets.',
  },
  {
    id: 'naics-code',
    term: 'NAICS Code',
    short: 'North American Industry Classification System code.',
    definition:
      'A NAICS code (North American Industry Classification System) is a widely used identifier that classifies industries and businesses by their primary economic activity. It helps define markets and align on their scope — here, NAICS 325412 (Pharmaceutical Preparation Manufacturing), narrowed to the Sterile Fill-Finish segment.',
    sources: [{ label: 'naics.com', href: 'https://www.naics.com/' }],
  },
  {
    id: 'value-network',
    term: 'Value Network',
    short: 'The full ecosystem within a market required to produce its output.',
    definition:
      'A value network is the entire ecosystem within a market required to produce the market output. Think of the market as one big virtual company holding every process, department, machine, service and material needed to make its output. For sterile fill-finish that spans aseptic filling and stoppering, contamination-control barrier systems, cleanroom HVAC, compounding, and the qualification and maintenance services around them.',
  },
  {
    id: 'value-network-level',
    term: 'Value Network Levels (L7–L3)',
    short: 'The depth of a unit in the value-network tree.',
    definition:
      'Value-network units are organised into levels by depth. L7 is the top-level market production system; L6 and L6a are major stages and sub-stages; L5 units are the systems and machines typically procured as products; L4 and L3 are the modules and components beneath them. In this report depth is shown as a colour shade — darkest at L7, lightest at L3.',
  },
  {
    id: 'core-functional-job-of-a-unit',
    term: 'Core Functional Job (of a unit)',
    short: 'The functional job a value-network unit exists to perform.',
    definition:
      'Every value-network unit carries a core functional job (CFJ) describing, solution-agnostically, what that unit exists to accomplish within the market’s production system — the anchor from which its stakeholders’ needs are derived.',
  },
  {
    id: 'product-match',
    term: 'Product Match',
    short: 'A supplier product mapped onto a value-network unit.',
    definition:
      'A product match links a company’s product to the value-network unit it serves. In this report, matches are shown for Waldner Process and Automation Solutions only: matched units are marked with a product box in the tree, with a trail highlighting the path down to them.',
  },
  {
    id: 'unspsc-code',
    term: 'UNSPSC Code',
    short: 'United Nations product & service taxonomy code.',
    definition:
      'A UNSPSC code (United Nations Standard Products and Services Code) is a widely used identifier for groups of products or services that share a common use or function, allowing an apples-to-apples comparison across products irrespective of brand name.',
    sources: [{ label: 'unspsc.org', href: 'https://www.unspsc.org/' }],
  },
]

/** All terms, sorted alphabetically by `term` (locale-aware). */
export const glossaryTerms: GlossaryTerm[] = [...terms].sort((a, b) =>
  a.term.localeCompare(b.term),
)

/** Resolve a deep-link key (an id or a term label) to a glossary entry. */
export function findTerm(key: string | undefined): GlossaryTerm | undefined {
  if (!key) return undefined
  const k = key.toLowerCase()
  return glossaryTerms.find(
    (t) => t.id === k || t.term.toLowerCase() === k,
  )
}
